/**
 * `trace-gateway` hot-path load profile — ROADMAP Phase 2 TARGETS.
 *
 * The targets this script exists to measure are **p99 < 100 ms, p50 < 20 ms at
 * 500 TPS sustained** with **zero 5xx over a 10-minute run**. Nothing here
 * decides whether they were met: `scripts/load_gateway.py` reads the summary
 * this script writes and asserts the exit conditions mechanically. A threshold
 * in k6 makes the process exit non-zero early, which is useful, but a phase
 * exit condition that lived only in a k6 threshold could be edited in the same
 * commit that failed it and nobody would see a diff worth reading
 * (CLAUDE.md §16, §17).
 *
 * **Why the load is generated by a container and not a local binary.** This is a
 * measurement instrument. A k6 on someone's PATH is whatever Homebrew installed
 * last week, and two runs of "the same" benchmark on different versions are not
 * comparable — but they look comparable, which is worse. The image is pinned by
 * tag AND digest in `pyproject.toml` `[tool.trace_x.tools]` (ADR-0038), for the
 * same reason the Python dependencies live in a hashed lockfile. The runner
 * refuses to use anything else.
 *
 * **Why the traffic is varied and skewed rather than repeated.** Every request
 * carries a fresh `X-Idempotency-Key`, so no request is served from the replay
 * cache: a repeated key would make every iteration after the first a cache read
 * and the run would report the latency of Redis `GET`, not of the scoring path.
 * For the same reason accounts, merchants, devices, IPs, amounts, channels and
 * event times all vary. They vary *with skew* rather than uniformly, because
 * both extremes measure the wrong thing: one account means one hot Redis key and
 * a perfectly warm rule path, while a uniform spread over a large key space
 * means every feature read is a miss and every account has insufficient history.
 * Real card traffic is heavy-tailed, and the hot path's cost depends on which it
 * is (ADR-0034's exact/approximate split is keyed on exactly this).
 *
 * **Why the entity pools are seeded.** Determinism where it is achievable
 * (CLAUDE.md §3.5): the same `SEED` produces the same traffic shape, so two runs
 * differ by the system under test rather than by the load. `Math.random()` is not
 * seedable, so the generator is explicit.
 *
 * Run it through `make load-gateway` — never `k6 run` by hand, which would skip
 * the run record and leave a number nobody can attribute (CLAUDE.md §13).
 */

import http from 'k6/http';
import exec from 'k6/execution';
import { Counter, Trend } from 'k6/metrics';

// --------------------------------------------------------------- inputs ----
// All optional at init time. `k6 inspect` executes this module to derive the
// options, and a parse check that required a live token and a running gateway
// would not be a parse check.

const BASE_URL = (__ENV.BASE_URL || 'http://host.docker.internal:8010').replace(/\/+$/, '');
const TOKEN = __ENV.TRACE_LOAD_TOKEN || '';
const TARGET_TPS = Number(__ENV.TARGET_TPS || 500);
const DURATION = __ENV.DURATION || '10m';
const SEED = Number(__ENV.SEED || 20260912);
const PRE_ALLOCATED_VUS = Number(__ENV.PRE_ALLOCATED_VUS || 120);
const MAX_VUS = Number(__ENV.MAX_VUS || 800);
const SUMMARY_PATH = __ENV.SUMMARY_PATH || '/out/summary.json';

/**
 * Unique per invocation, supplied by the runner.
 *
 * The idempotency cache outlives the run. Without a per-run nonce in the key,
 * the second execution of this script would replay the first one's cached
 * responses end to end and report a latency that never touched the scorer —
 * a benchmark that gets *faster* the more often you run it.
 */
const RUN_NONCE = __ENV.RUN_NONCE || 'no-nonce';

// ------------------------------------------------------------- metrics -----
// Every counter is written on every iteration, with 0 where the condition did
// not hold. A metric that only appears when something goes wrong is absent from
// a clean run, and the post-processor cannot tell "zero 5xx" from "5xx were
// never counted" — so it would have to treat a good run as unproven.

const http5xx = new Counter('gateway_http_5xx');
const http4xx = new Counter('gateway_http_4xx');
const http429 = new Counter('gateway_http_429');
const http2xx = new Counter('gateway_http_2xx');
const degraded = new Counter('gateway_degraded_responses');
const unparseable = new Counter('gateway_unparseable_responses');
const bandLow = new Counter('gateway_band_low');
const bandMedium = new Counter('gateway_band_medium');
const bandHigh = new Counter('gateway_band_high');
const bandCritical = new Counter('gateway_band_critical');

/**
 * The gateway's own view of its latency, taken from `RiskDecision.latency_ms`.
 *
 * Recorded beside `http_req_duration` rather than instead of it. The budget in
 * ROADMAP Phase 2 is what a caller experiences, so the client-side figure is the
 * one that decides the target; the server-side figure is what attributes a miss
 * to the scoring path rather than to the network, the event loop or the load
 * generator itself.
 */
const serverLatency = new Trend('gateway_server_latency_ms');

export const options = {
  scenarios: {
    // Open model, deliberately. `constant-arrival-rate` keeps sending at the
    // target rate no matter how slow the responses get, which is what "500 TPS
    // sustained" means. A closed model (N VUs looping) would quietly reduce the
    // offered load as latency rose, so a gateway that fell over would report a
    // lower TPS and a flattering p99 instead of a failure.
    hot_path: {
      executor: 'constant-arrival-rate',
      rate: TARGET_TPS,
      timeUnit: '1s',
      duration: DURATION,
      preAllocatedVUs: PRE_ALLOCATED_VUS,
      maxVUs: MAX_VUS,
      gracefulStop: '30s',
    },
  },
  // p(50) is requested explicitly: the ROADMAP target is stated as p50, and
  // k6's default trend stats report `med`, which is the same statistic under a
  // different name. Reporting it under the name the target uses removes the
  // step where a reader has to know that.
  summaryTrendStats: ['min', 'avg', 'med', 'p(50)', 'p(90)', 'p(95)', 'p(99)', 'max', 'count'],
  thresholds: {
    // A fast fail while the run is in flight. The binding assertion is in
    // `scripts/load_gateway.py`; these exist so a broken run stops in minute one
    // instead of minute ten.
    gateway_http_5xx: ['count==0'],
    http_req_duration: ['p(99)<100', 'p(50)<20'],
    // `dropped_iterations` counts the iterations the arrival-rate executor
    // could not start, i.e. the offered load that never left the generator. A
    // run that dropped any of them did not sustain the target rate, so its
    // latency figures describe a smaller test than the one being claimed.
    //
    // The threshold is also what makes the metric *appear*: verified against
    // the pinned image, k6 omits `dropped_iterations` from the summary entirely
    // when nothing was dropped, and a post-processor that read its absence as
    // zero would be inferring a measurement rather than reading one. Declaring
    // a threshold registers it, so the summary always carries the count.
    dropped_iterations: ['count==0'],
  },
  // The response body is the only place the band, the degraded flag and the
  // server-side latency appear, so it cannot be discarded.
  discardResponseBodies: false,
};

// ------------------------------------------------- deterministic traffic ----

/** mulberry32 — a small, seedable PRNG. Not cryptographic, and never used as if
 * it were: its only job is to make the traffic shape reproducible. */
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Pool sizes. Large enough that a ten-minute run at 500 TPS (300k requests)
// does not exhaust them, small enough that accounts accumulate real history —
// which is the state the online features are actually read in.
const ACCOUNTS = 20000;
const MERCHANTS = 3000;
const DEVICES = 26000;
const IPS = 9000;

/** The heavy tail, quantified: 80% of traffic from 5% of the entities. */
const HOT_FRACTION = 0.05;
const HOT_SHARE = 0.8;

const CHANNELS = [
  // Weighted to a card-not-present-heavy mix, and each channel paired with the
  // entry modes that can physically produce it. An uncorrelated pairing
  // (CARD_PRESENT + ECOMMERCE) would exercise rule branches that no real
  // acquirer ever sends, so the measured branch mix would not be the
  // production one.
  { weight: 0.5, channel: 'CARD_NOT_PRESENT', entryModes: ['ECOMMERCE', 'TOKEN'] },
  { weight: 0.33, channel: 'CARD_PRESENT', entryModes: ['CHIP', 'CONTACTLESS', 'MAGSTRIPE'] },
  { weight: 0.1, channel: 'ATM', entryModes: ['CHIP'] },
  { weight: 0.05, channel: 'RECURRING', entryModes: ['TOKEN'] },
  { weight: 0.02, channel: 'UNKNOWN', entryModes: ['UNKNOWN', 'MANUAL'] },
];

/**
 * Amounts in integer minor units, never a float (CLAUDE.md §6).
 *
 * Four magnitude bands rather than one value, because the rule pack's
 * thresholds are amount-dependent: a constant amount would put every
 * transaction on the same side of every comparison and the run would measure
 * one branch of the engine at 500 TPS.
 */
const AMOUNT_BANDS = [
  { weight: 0.55, min: 100, max: 5000 },
  { weight: 0.3, min: 5000, max: 25000 },
  { weight: 0.12, min: 25000, max: 150000 },
  { weight: 0.03, min: 150000, max: 900000 },
];

const CURRENCIES = ['USD', 'EUR', 'GBP'];
const COUNTRIES = ['US', 'GB', 'DE', 'FR', 'NL', 'CA', 'SG'];
const MCCS = ['5411', '5812', '5999', '4111', '6011', '7995', '5732'];

function pad(value, width) {
  return String(value).padStart(width, '0');
}

/** Pick an index with the heavy tail described above. */
function skewedIndex(rnd, size) {
  const hot = Math.max(1, Math.floor(size * HOT_FRACTION));
  if (rnd() < HOT_SHARE) {
    return 1 + Math.floor(rnd() * hot);
  }
  return 1 + hot + Math.floor(rnd() * (size - hot));
}

function weightedPick(rnd, table) {
  let roll = rnd();
  for (const entry of table) {
    roll -= entry.weight;
    if (roll <= 0) {
      return entry;
    }
  }
  return table[table.length - 1];
}

function choice(rnd, values) {
  return values[Math.floor(rnd() * values.length)];
}

/**
 * One transaction, shaped like the released `tx.raw.v1` contract.
 *
 * Identifier spellings are the ones `TransactionRequest` enforces
 * (`acct_\d{6,}`, `mrch_\d{5,}`, `dev_\d{6,}`, `ip_\d{5,}`, `card_\d{6,}`). A
 * malformed id would be rejected with a 422 before any scoring happened, and
 * the run would report the latency of the validation layer.
 */
function buildTransaction(rnd, sequence) {
  const account = skewedIndex(rnd, ACCOUNTS);
  const channel = weightedPick(rnd, CHANNELS);
  const amountBand = weightedPick(rnd, AMOUNT_BANDS);
  const amount = Math.floor(amountBand.min + rnd() * (amountBand.max - amountBand.min));

  // Event time trails processing time by up to 30 s, as a real acquirer feed
  // does. Never in the future: `occurred_at` more than 24 h ahead is rejected as
  // clock skew, and an event time equal to `now` on every request would hide any
  // event-time handling bug behind a perfectly ordered stream (ADR-0026).
  const occurredAt = new Date(Date.now() - Math.floor(rnd() * 30000)).toISOString();

  const body = {
    transaction_id: `tx_${RUN_NONCE}_${sequence}`,
    account_id: `acct_${pad(account, 6)}`,
    amount_minor: amount,
    currency: choice(rnd, CURRENCIES),
    occurred_at: occurredAt,
    card_id: `card_${pad(account, 6)}`,
    device_id: `dev_${pad(skewedIndex(rnd, DEVICES), 6)}`,
    merchant_id: `mrch_${pad(skewedIndex(rnd, MERCHANTS), 5)}`,
    ip_id: `ip_${pad(skewedIndex(rnd, IPS), 5)}`,
    channel: channel.channel,
    entry_mode: choice(rnd, channel.entryModes),
    merchant_mcc: choice(rnd, MCCS),
    merchant_country: choice(rnd, COUNTRIES),
    authorization_outcome: rnd() < 0.95 ? 'APPROVED' : 'DECLINED',
  };

  // Geolocation on most but not all requests: `unavailable_features` is a
  // first-class outcome (ADR-0022), and a feed where every field is always
  // present would never exercise the absent-input path that production hits.
  if (rnd() < 0.85) {
    body.latitude = Math.round((rnd() * 140 - 70) * 1e4) / 1e4;
    body.longitude = Math.round((rnd() * 340 - 170) * 1e4) / 1e4;
  }
  // Attacker-controlled fields (docs/SECURITY.md §5.1), populated with benign
  // values. This run measures throughput; the injection corpus is a separate
  // suite (`tests/adversarial/`) and mixing the two would make a latency figure
  // depend on how many attacks were in the sample.
  if (rnd() < 0.6) {
    body.merchant_name = `Merchant ${pad(skewedIndex(rnd, MERCHANTS), 5)}`;
  }
  return body;
}

export function setup() {
  // Fail before the first request rather than after 300,000 of them. A run
  // without a token measures the 401 path at 500 TPS and reports it as a p99.
  if (!TOKEN) {
    throw new Error(
      'TRACE_LOAD_TOKEN is empty. The gateway authenticates every request ' +
        '(docs/SECURITY.md §3, Plane B); without a token this run would measure ' +
        'the 401 path. Run it through `make load-gateway`.'
    );
  }
  if (RUN_NONCE === 'no-nonce') {
    throw new Error(
      'RUN_NONCE was not supplied. Idempotency keys would collide with a ' +
        'previous run and the replay cache would serve most of this one.'
    );
  }
  return { startedAt: new Date().toISOString() };
}

export default function () {
  // Seeded per VU so the streams are independent but reproducible; the PRNG is
  // rebuilt per iteration from the global iteration number so that a VU
  // restarting mid-run cannot repeat a stretch of traffic it already sent.
  const iteration = exec.scenario.iterationInTest;
  const rnd = mulberry32(SEED + exec.vu.idInTest * 1000003 + iteration);
  const body = buildTransaction(rnd, iteration);

  const response = http.post(`${BASE_URL}/v1/transactions`, JSON.stringify(body), {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${TOKEN}`,
      // Unique per request, per run. Required on every mutating POST — the
      // gateway returns 400 without one — and a reused value would turn the
      // rest of the run into replay-cache reads.
      'X-Idempotency-Key': `${RUN_NONCE}-${exec.vu.idInTest}-${iteration}`,
    },
    // One tag for every request, so `http_req_duration` in the summary is this
    // endpoint and not an average across whatever else a future script adds.
    tags: { name: 'POST /v1/transactions' },
  });

  const status = response.status;
  http2xx.add(status >= 200 && status < 300 ? 1 : 0);
  http4xx.add(status >= 400 && status < 500 ? 1 : 0);
  http429.add(status === 429 ? 1 : 0);
  http5xx.add(status >= 500 ? 1 : 0);

  let decision = null;
  if (status === 200) {
    try {
      decision = JSON.parse(response.body);
    } catch (err) {
      decision = null;
    }
  }
  unparseable.add(status === 200 && decision === null ? 1 : 0);

  // Counted from the response body rather than the header so the figure comes
  // from the contract (`RiskDecision.degraded`) rather than from a transport
  // detail that a proxy could strip.
  degraded.add(decision && decision.degraded ? 1 : 0);
  bandLow.add(decision && decision.risk_band === 'LOW' ? 1 : 0);
  bandMedium.add(decision && decision.risk_band === 'MEDIUM' ? 1 : 0);
  bandHigh.add(decision && decision.risk_band === 'HIGH' ? 1 : 0);
  bandCritical.add(decision && decision.risk_band === 'CRITICAL' ? 1 : 0);
  if (decision && typeof decision.latency_ms === 'number') {
    serverLatency.add(decision.latency_ms);
  }
}

/**
 * Write the machine-readable summary the Python post-processor reads.
 *
 * The default text summary is replaced rather than supplemented from
 * `https://jslib.k6.io/…`: fetching a helper over the network at run time would
 * make a pinned instrument depend on an unpinned remote, which is the exact
 * failure ADR-0038 pins the image to avoid. The short line printed here is for
 * the human watching; `scripts/load_gateway.py` renders the report.
 */
export function handleSummary(data) {
  const metric = (name, stat) => {
    const entry = data.metrics[name];
    return entry && entry.values && entry.values[stat] !== undefined ? entry.values[stat] : 'n/a';
  };
  const out = {};
  out[SUMMARY_PATH] = JSON.stringify(data, null, 2);
  out.stdout =
    `\nk6 finished. requests=${metric('http_reqs', 'count')} ` +
    `p50=${metric('http_req_duration', 'p(50)')}ms ` +
    `p99=${metric('http_req_duration', 'p(99)')}ms ` +
    `5xx=${metric('gateway_http_5xx', 'count')} ` +
    `dropped=${metric('dropped_iterations', 'count')}\n` +
    `Nothing above is a published result until scripts/load_gateway.py records ` +
    `it (CLAUDE.md §13).\n`;
  return out;
}
