"""GENERATED FROM docs/contracts/events/ -- DO NOT EDIT BY HAND.

JSON Schema is the source of truth for events (ADR-0026, ADR-0028). Change the
schema, then run `make codegen`. A CI gate runs the same command and fails on
any diff, so an edit made here is reverted rather than merged.
"""

# generated by datamodel-codegen:
#   filename:  device.events.v1.json

from __future__ import annotations

from enum import StrEnum

from pydantic import ConfigDict, Field

from trace_core.contracts.base import StrictEventModel

from . import envelope_v1


class DeviceEventType(StrEnum):
    FIRST_SEEN = "FIRST_SEEN"
    FINGERPRINT_CHANGED = "FINGERPRINT_CHANGED"
    ATTRIBUTE_CHANGED = "ATTRIBUTE_CHANGED"
    UNKNOWN = "UNKNOWN"


class Payload(StrictEventModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    device_id: str = Field(..., pattern="^dev_\\d{6,}$")
    account_id: str = Field(..., pattern="^acct_\\d{6,}$")
    device_event_type: DeviceEventType
    platform: str = Field(..., max_length=32)
    ip_id: str | None = Field(None, pattern="^ip_\\d{5,}$")
    device_label: str | None = Field(None, max_length=128)
    """
    ATTACKER-CONTROLLED: a client-supplied device name.
    """


class DeviceEventV1(StrictEventModel):
    """
    A device fingerprint observation. Topic device.events.v1, keyed by device_id because device-sharing detection is order-sensitive on the device, not the account (docs/EVENT_CONTRACTS.md §3).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    envelope: envelope_v1.EventEnvelope
    payload: Payload
