"""GENERATED FROM docs/contracts/events/ -- DO NOT EDIT BY HAND.

JSON Schema is the source of truth for events (ADR-0026, ADR-0028). Change the
schema, then run `make codegen`. A CI gate runs the same command and fails on
any diff, so an edit made here is reverted rather than merged.
"""

# generated by datamodel-codegen:
#   filename:  envelope.v1.json

from __future__ import annotations

from pydantic import AwareDatetime, ConfigDict, Field

from trace_core.contracts.base import StrictEventModel


class EventEnvelope(StrictEventModel):
    """
    Mandatory envelope on every TRACE-X event (docs/EVENT_CONTRACTS.md §2, ADR-0026). Envelope fields are never nested inside payload, and payload never redefines one.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: str = Field(
        ...,
        pattern="^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    )
    """
    UUIDv7, lowercase. Time-ordered, and the deduplication key in both Redis (hot path) and Spark dropDuplicatesWithinWatermark (warm path). Carries a pattern rather than "format": "uuid" on purpose: format only says it is a UUID, while the pattern pins the VERSION NIBBLE to 7, and time-ordering is the property the dedup key and Delta index locality actually depend on.
    """
    event_type: str = Field(..., max_length=64, pattern="^[a-z][a-z0-9]*(\\.[a-z][a-z0-9]*)+$")
    """
    Dotted and stable. Renaming is a breaking change.
    """
    schema_version: int = Field(..., ge=1)
    """
    Matches the file suffix. Never decreases.
    """
    occurred_at: AwareDatetime
    """
    EVENT TIME. Drives every window and watermark. Never interchangeable with ingested_at (ADR-0026).
    """
    ingested_at: AwareDatetime
    """
    PROCESSING TIME. Lag measurement only; never used for business logic.
    """
    producer: str = Field(..., max_length=64, pattern="^[a-z][a-z0-9-]*@\\d+\\.\\d+\\.\\d+$")
    """
    service@semver, for provenance and blast-radius analysis.
    """
    trace_id: str = Field(..., pattern="^[0-9a-f]{32}$")
    """
    W3C trace id, propagated as a Kafka header AND in the body: headers survive Spark's transformations, bodies survive header-stripping intermediaries.
    """
    correlation_id: str = Field(..., max_length=64, min_length=1)
    """
    Business flow id, stable across a whole investigation.
    """
    idempotency_key: str = Field(..., pattern="^sha256:[0-9a-f]{64}$")
    """
    Deterministic hash of the semantic content. Equal keys mean equal meaning.
    """
