"""GENERATED FROM docs/contracts/events/ -- DO NOT EDIT BY HAND.

JSON Schema is the source of truth for events (ADR-0026, ADR-0028). Change the
schema, then run `make codegen`. A CI gate runs the same command and fails on
any diff, so an edit made here is reverted rather than merged.
"""

# generated by datamodel-codegen:
#   filename:  identity.events.v1.json

from __future__ import annotations

from enum import StrEnum

from pydantic import ConfigDict, Field

from trace_core.contracts.base import StrictEventModel

from . import envelope_v1


class IdentityEventType(StrEnum):
    PASSWORD_CHANGE = "PASSWORD_CHANGE"
    EMAIL_CHANGE = "EMAIL_CHANGE"
    PHONE_CHANGE = "PHONE_CHANGE"
    ADDRESS_CHANGE = "ADDRESS_CHANGE"
    MFA_RESET = "MFA_RESET"
    MFA_ENROLLED = "MFA_ENROLLED"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED"
    UNKNOWN = "UNKNOWN"


class Payload(StrictEventModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str = Field(..., pattern="^acct_\\d{6,}$")
    identity_event_type: IdentityEventType
    device_id: str | None = Field(None, pattern="^dev_\\d{6,}$")
    ip_id: str | None = Field(None, pattern="^ip_\\d{5,}$")
    user_agent: str | None = Field(None, max_length=256)
    """
    ATTACKER-CONTROLLED: a client-supplied header.
    """


class IdentityEventV1(StrictEventModel):
    """
    A change to an account holder's identity or credentials. Topic identity.events.v1, keyed by account_id. The account-takeover signature depends on ordering these against transactions.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    envelope: envelope_v1.EventEnvelope
    payload: Payload
