"""GENERATED FROM docs/contracts/events/ -- DO NOT EDIT BY HAND.

JSON Schema is the source of truth for events (ADR-0026, ADR-0028). Change the
schema, then run `make codegen`. A CI gate runs the same command and fails on
any diff, so an edit made here is reverted rather than merged.
"""

# generated by datamodel-codegen:
#   filename:  investigation.requested.v1.json

from __future__ import annotations

from enum import StrEnum

from pydantic import ConfigDict, Field, RootModel

from trace_core.contracts.base import StrictEventModel

from . import envelope_v1


class RiskBand(StrEnum):
    """
    Only HIGH and CRITICAL open an investigation (docs/ARCHITECTURE.md §3). LOW and MEDIUM are absent from this enum deliberately: a message carrying one would mean triage fired when it should not have.
    """

    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FeatureSource(StrEnum):
    """
    Whether the warm path had reconciled the features this decision read. Consumers must tolerate an unseen value (docs/EVENT_CONTRACTS.md §4).
    """

    ONLINE_ONLY = "ONLINE_ONLY"
    RECONCILED = "RECONCILED"


class DegradedReason(RootModel[str]):
    root: str = Field(..., max_length=64)


class FiredRuleId(RootModel[str]):
    root: str = Field(..., pattern="^R\\d{3}_[a-z0-9_]+$")


class Payload(StrictEventModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    case_id: str = Field(..., pattern="^case_[0-9a-f]{32}$")
    """
    The case this request is for. Distinct from an investigation_id: the case is what an analyst sees and exists at triage time, while an investigation is how the orchestrator runs and is created by the worker that leases it (ADR-0027).
    """
    transaction_id: str = Field(..., max_length=64, min_length=1)
    account_id: str = Field(..., pattern="^acct_\\d{6,}$")
    risk_band: RiskBand
    """
    Only HIGH and CRITICAL open an investigation (docs/ARCHITECTURE.md §3). LOW and MEDIUM are absent from this enum deliberately: a message carrying one would mean triage fired when it should not have.
    """
    score: float = Field(..., ge=0.0, le=1.0)
    """
    Combined rules score at triage time, bounded [0, 1].
    """
    rule_pack_id: str = Field(..., max_length=64, min_length=1)
    rule_pack_digest: str = Field(..., pattern="^sha256:[0-9a-f]{64}$")
    """
    sha256 of the rule pack that produced the decision. Rules hot-reload, so without this a consumer cannot tell which behaviour opened the case.
    """
    threshold_config_digest: str = Field(..., pattern="^sha256:[0-9a-f]{64}$")
    """
    sha256 of the banding configuration in force at triage time.
    """
    feature_set_version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    """
    Semantic version of the online feature set (ADR-0032). A score produced by a different feature set is not comparable to one produced by this one.
    """
    feature_source: FeatureSource
    """
    Whether the warm path had reconciled the features this decision read. Consumers must tolerate an unseen value (docs/EVENT_CONTRACTS.md §4).
    """
    degraded: bool
    """
    True when the decision was made with a dependency unavailable. Every fail-open decision is tagged and counted (CLAUDE.md §3.7), and an investigation opened on degraded features is weaker evidence than one opened on complete features.
    """
    degraded_reasons: list[DegradedReason] | None = Field(None, max_length=16)
    """
    Why the decision was degraded, when it was.
    """
    fired_rule_ids: list[FiredRuleId] = Field(..., max_length=200)
    """
    The rules that fired, so a consumer knows what to investigate without re-deriving the decision. Rule IDS ONLY: the feature values a predicate read stay in the synchronous response and the case record, because this topic is retained for 30 days and an event is a poor place for data that is already stored.
    """
    abstained_rule_count: int | None = Field(None, ge=0)
    """
    How many rules could not reach a verdict because an input was absent. Carried so a consumer can tell a decision made with a blind pack from one made with a quiet one (ADR-0032, ADR-0033).
    """


class InvestigationRequestedV1(StrictEventModel):
    """
    Triage opened a case and is asking for an investigation. Topic investigation.requested.v1, keyed by case_id because one message exists per case and the case is the entity that exists at produce time (docs/EVENT_CONTRACTS.md §3). Written to the transactional outbox in the SAME database transaction as the case and queue rows, so the event cannot announce a case that does not exist (ADR-0007).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    envelope: envelope_v1.EventEnvelope
    payload: Payload
