"""GENERATED FROM docs/contracts/events/ -- DO NOT EDIT BY HAND.

JSON Schema is the source of truth for events (ADR-0026, ADR-0028). Change the
schema, then run `make codegen`. A CI gate runs the same command and fails on
any diff, so an edit made here is reverted rather than merged.
"""

# generated by datamodel-codegen:
#   filename:  tx.authorization.v1.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, ConfigDict, Field

from trace_core.contracts.base import StrictEventModel

from . import envelope_v1


class AuthorizationOutcome(StrEnum):
    """
    What the authorization system decided. UNKNOWN carries no observation and REVERSED is a later event with other semantics, so neither is an outcome here.
    """

    APPROVED = "APPROVED"
    DECLINED = "DECLINED"


class Payload(StrictEventModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    transaction_id: str = Field(..., max_length=64, min_length=1)
    """
    The transaction this outcome belongs to: the same value as its tx.raw.v1 payload.transaction_id.
    """
    account_id: str = Field(..., pattern="^acct_\\d{6,}$")
    authorization_outcome: AuthorizationOutcome
    """
    What the authorization system decided. UNKNOWN carries no observation and REVERSED is a later event with other semantics, so neither is an outcome here.
    """
    transaction_occurred_at: AwareDatetime
    """
    The transaction's event time, copied. The envelope's occurred_at is the outcome time.
    """


class TxAuthorizationV1(StrictEventModel):
    """
    One authorization outcome for one transaction, dated when the authorization system decided. Topic tx.authorization.v1, keyed by account_id and deduplicated by payload.transaction_id. A transaction's own outcome never reaches its own features (ADR-0049).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    envelope: envelope_v1.EventEnvelope
    payload: Payload
