"""GENERATED FROM docs/contracts/events/ -- DO NOT EDIT BY HAND.

JSON Schema is the source of truth for events (ADR-0026, ADR-0028). Change the
schema, then run `make codegen`. A CI gate runs the same command and fails on
any diff, so an edit made here is reverted rather than merged.
"""

# generated by datamodel-codegen:
#   filename:  tx.raw.v1.json

from __future__ import annotations

from enum import StrEnum

from pydantic import ConfigDict, Field

from trace_core.contracts.base import StrictEventModel

from . import envelope_v1


class Channel(StrEnum):
    """
    Consumers must tolerate an unseen value (docs/EVENT_CONTRACTS.md §4).
    """

    CARD_PRESENT = "CARD_PRESENT"
    CARD_NOT_PRESENT = "CARD_NOT_PRESENT"
    ATM = "ATM"
    RECURRING = "RECURRING"
    UNKNOWN = "UNKNOWN"


class EntryMode(StrEnum):
    CHIP = "CHIP"
    CONTACTLESS = "CONTACTLESS"
    MAGSTRIPE = "MAGSTRIPE"
    MANUAL = "MANUAL"
    ECOMMERCE = "ECOMMERCE"
    TOKEN = "TOKEN"
    UNKNOWN = "UNKNOWN"


class AuthorizationOutcome(StrEnum):
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"
    REVERSED = "REVERSED"
    UNKNOWN = "UNKNOWN"


class Payload(StrictEventModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    transaction_id: str = Field(..., max_length=64, min_length=1)
    account_id: str = Field(..., pattern="^acct_\\d{6,}$")
    card_id: str = Field(..., pattern="^card_\\d{6,}$")
    device_id: str = Field(..., pattern="^dev_\\d{6,}$")
    merchant_id: str = Field(..., pattern="^mrch_\\d{5,}$")
    ip_id: str = Field(..., pattern="^ip_\\d{5,}$")
    amount_minor: int = Field(..., ge=-100000000000, le=100000000000)
    """
    Integer minor units. NEVER a float (CLAUDE.md §6). Signed: a refund is negative.
    """
    currency: str = Field(..., pattern="^[A-Z]{3}$")
    """
    ISO 4217 alphabetic code.
    """
    channel: Channel
    """
    Consumers must tolerate an unseen value (docs/EVENT_CONTRACTS.md §4).
    """
    entry_mode: EntryMode
    merchant_mcc: str = Field(..., pattern="^\\d{4}$")
    merchant_country: str = Field(..., pattern="^[A-Z]{2}$")
    merchant_name: str | None = Field(None, max_length=128)
    """
    ATTACKER-CONTROLLED: set at merchant registration. Primary prompt-injection surface (docs/SECURITY.md §T1). Stamped trust_tier=UNTRUSTED in Bronze and never loses it.
    """
    latitude: float = Field(..., ge=-90.0, le=90.0)
    longitude: float = Field(..., ge=-180.0, le=180.0)
    user_agent: str | None = Field(None, max_length=256)
    """
    ATTACKER-CONTROLLED: a client-supplied header.
    """
    memo: str | None = Field(None, max_length=256)
    """
    ATTACKER-CONTROLLED: free text accompanying the payment.
    """
    authorization_outcome: AuthorizationOutcome


class TxRawV1(StrictEventModel):
    """
    A transaction as it arrived, before scoring. Topic tx.raw.v1, keyed by account_id because per-account velocity is order-sensitive (docs/EVENT_CONTRACTS.md §3).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    envelope: envelope_v1.EventEnvelope
    payload: Payload
