"""GENERATED FROM docs/contracts/events/ -- DO NOT EDIT BY HAND.

JSON Schema is the source of truth for events (ADR-0026, ADR-0028). Change the
schema, then run `make codegen`. A CI gate runs the same command and fails on
any diff, so an edit made here is reverted rather than merged.
"""

# generated by datamodel-codegen:
#   filename:  tx.scored.v1.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, ConfigDict, Field, RootModel

from trace_core.contracts.base import StrictEventModel

from . import envelope_v1


class Channel(StrEnum):
    """
    Consumers must tolerate an unseen value (docs/EVENT_CONTRACTS.md §4).
    """

    CARD_PRESENT = "CARD_PRESENT"
    CARD_NOT_PRESENT = "CARD_NOT_PRESENT"
    ATM = "ATM"
    RECURRING = "RECURRING"
    UNKNOWN = "UNKNOWN"


class EntryMode(StrEnum):
    CHIP = "CHIP"
    CONTACTLESS = "CONTACTLESS"
    MAGSTRIPE = "MAGSTRIPE"
    MANUAL = "MANUAL"
    ECOMMERCE = "ECOMMERCE"
    TOKEN = "TOKEN"
    UNKNOWN = "UNKNOWN"


class AuthorizationOutcome(StrEnum):
    APPROVED = "APPROVED"
    DECLINED = "DECLINED"
    REVERSED = "REVERSED"
    UNKNOWN = "UNKNOWN"


class FieldCoverageEnum(StrEnum):
    transaction_id = "transaction_id"
    account_id = "account_id"
    card_id = "card_id"
    device_id = "device_id"
    merchant_id = "merchant_id"
    ip_id = "ip_id"
    amount_minor = "amount_minor"
    currency = "currency"
    occurred_at = "occurred_at"
    ingested_at = "ingested_at"
    channel = "channel"
    entry_mode = "entry_mode"
    merchant_mcc = "merchant_mcc"
    merchant_country = "merchant_country"
    merchant_name = "merchant_name"
    latitude = "latitude"
    longitude = "longitude"
    user_agent = "user_agent"
    memo = "memo"
    authorization_outcome = "authorization_outcome"


class Decision(StrEnum):
    APPROVE = "APPROVE"
    FLAG = "FLAG"
    DECLINE = "DECLINE"


class RiskBand(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class DegradedReason(RootModel[str]):
    root: str = Field(..., max_length=64, min_length=1)


class BandFloor(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FiredRule(StrictEventModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rule_id: str = Field(..., max_length=64, min_length=1)
    rule_version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    weight: float = Field(..., ge=0.0, le=1.0)
    band_floor: BandFloor | None = None


class FeatureSource(StrEnum):
    ONLINE_ONLY = "ONLINE_ONLY"
    RECONCILED = "RECONCILED"


class DecisionSummary(StrictEventModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    decision: Decision
    risk_band: RiskBand
    score: float = Field(..., ge=0.0, le=1.0)
    degraded: bool
    degraded_reasons: list[DegradedReason] = Field(..., max_length=32)
    fired_rules: list[FiredRule] = Field(..., max_length=256)
    rule_pack_id: str = Field(..., max_length=64, min_length=1)
    rule_pack_digest: str = Field(..., pattern="^sha256:[0-9a-f]{64}$")
    threshold_config_digest: str = Field(..., pattern="^sha256:[0-9a-f]{64}$")
    feature_set_version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    feature_source: FeatureSource
    case_id: str | None = Field(None, pattern="^case_[0-9a-f]{32}$")
    scored_at: AwareDatetime
    """
    PROCESSING TIME: when the decision was made. The transaction's event time is the envelope's occurred_at.
    """


class State(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"


class Source(StrEnum):
    ONLINE_ONLY = "ONLINE_ONLY"
    RECONCILED = "RECONCILED"


class MissingField(StrEnum):
    transaction_id = "transaction_id"
    account_id = "account_id"
    card_id = "card_id"
    device_id = "device_id"
    merchant_id = "merchant_id"
    ip_id = "ip_id"
    amount_minor = "amount_minor"
    currency = "currency"
    occurred_at = "occurred_at"
    ingested_at = "ingested_at"
    channel = "channel"
    entry_mode = "entry_mode"
    merchant_mcc = "merchant_mcc"
    merchant_country = "merchant_country"
    merchant_name = "merchant_name"
    latitude = "latitude"
    longitude = "longitude"
    user_agent = "user_agent"
    memo = "memo"
    authorization_outcome = "authorization_outcome"


class LookbackCompleteness(StrEnum):
    """
    Whether the store could vouch for the feature's whole lookback when it was served. For INSUFFICIENT_HISTORY, COMPLETE means the entity is genuinely new, and INCOMPLETE or UNKNOWN mean the store could not vouch. NOT_APPLICABLE for a feature with no lookback.
    """

    COMPLETE = "COMPLETE"
    INCOMPLETE = "INCOMPLETE"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ServedFeature(StrictEventModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    feature_id: str = Field(..., max_length=64, min_length=1)
    state: State
    value: float | None = None
    """
    Present exactly when state is AVAILABLE.
    """
    approximate: bool
    source: Source
    missing_fields: list[MissingField] = Field(..., max_length=32)
    """
    For UNAVAILABLE: the canonical fields the request did not supply.
    """
    lookback_completeness: LookbackCompleteness
    """
    Whether the store could vouch for the feature's whole lookback when it was served. For INSUFFICIENT_HISTORY, COMPLETE means the entity is genuinely new, and INCOMPLETE or UNKNOWN mean the store could not vouch. NOT_APPLICABLE for a feature with no lookback.
    """


class ObserveOutcome(StrEnum):
    """
    What happened to this transaction's write to the online store (ADR-0046 §5). The event is published whatever it was (ADR-0051 §3).
    """

    RECORDED = "RECORDED"
    REDELIVERY = "REDELIVERY"
    CONFLICT = "CONFLICT"
    REFUSED = "REFUSED"
    UNREACHABLE = "UNREACHABLE"
    SKIPPED = "SKIPPED"


class Payload(StrictEventModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    transaction_id: str = Field(..., max_length=64, min_length=1)
    account_id: str = Field(..., pattern="^acct_\\d{6,}$")
    card_id: str | None = Field(None, pattern="^card_\\d{6,}$")
    device_id: str | None = Field(None, pattern="^dev_\\d{6,}$")
    merchant_id: str | None = Field(None, pattern="^mrch_\\d{5,}$")
    ip_id: str | None = Field(None, pattern="^ip_\\d{5,}$")
    amount_minor: int = Field(..., ge=-9223372036854775808, le=9223372036854775807)
    """
    Integer minor units as the API accepted them. NEVER a float (CLAUDE.md §6). Signed: a refund is negative. Bounded by a signed 64-bit integer, the width every consumer parses.
    """
    currency: str = Field(..., pattern="^[A-Z]{3}$")
    """
    ISO 4217 alphabetic code.
    """
    channel: Channel | None = None
    """
    Consumers must tolerate an unseen value (docs/EVENT_CONTRACTS.md §4).
    """
    entry_mode: EntryMode | None = None
    merchant_mcc: str | None = Field(None, pattern="^\\d{4}$")
    merchant_country: str | None = Field(None, pattern="^[A-Z]{2}$")
    merchant_name: str | None = Field(None, max_length=128)
    """
    ATTACKER-CONTROLLED: set at merchant registration, carried as served. Stamped trust_tier=UNTRUSTED and never loses it.
    """
    latitude: float | None = Field(None, ge=-90.0, le=90.0)
    longitude: float | None = Field(None, ge=-180.0, le=180.0)
    user_agent: str | None = Field(None, max_length=256)
    """
    ATTACKER-CONTROLLED: a client-supplied header.
    """
    memo: str | None = Field(None, max_length=256)
    """
    ATTACKER-CONTROLLED: free text accompanying the payment.
    """
    authorization_outcome: AuthorizationOutcome | None = None
    field_coverage: list[FieldCoverageEnum] = Field(..., max_length=32)
    """
    Which canonical fields the request supplied. An optional transaction field is present in the payload exactly when it is listed here.
    """
    decision_summary: DecisionSummary
    served_features: list[ServedFeature] = Field(..., max_length=512)
    """
    Every feature the decision read, one entry each: an extensible collection, so a later feature set needs no new schema.
    """
    observe_outcome: ObserveOutcome
    """
    What happened to this transaction's write to the online store (ADR-0046 §5). The event is published whatever it was (ADR-0051 §3).
    """
    store_position: int | None = Field(..., ge=0)
    """
    The store's observation counter after the write; null when the store did not answer or was not asked.
    """
    store_epoch: AwareDatetime | None
    """
    The store's recording epoch the position was counted in; null when unknown.
    """


class TxScoredV1(StrictEventModel):
    """
    One scored transaction as the gateway served it: the transaction, the decision, every feature value the decision read, and what the online store did with the transaction. Topic tx.scored.v1, keyed by account_id and deduplicated by payload.transaction_id. The durable observation log of the online store (ADR-0051): the producer session and sequence number travel as the tracex-session-id and tracex-seq headers, never in the payload, so no content depends on which session carried it. The envelope's occurred_at is the transaction's event time. Never labels, causal evidence keys or any evaluation-only data (PHASE3_PLAN §3 Q1).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    envelope: envelope_v1.EventEnvelope
    payload: Payload
