#!/usr/bin/env python3
"""Derive requirements-gateway.lock: the hashed runtime subset of requirements.lock.

The trace-gateway image needs the project's core dependencies and its `db`, `api` and
`obs` extras -- not pyspark and not the development tooling. Installing the whole lock
would put both into the hot-path image, and resolving a second dependency set would let
its versions drift from the ones every test ran against. So the runtime lock is DERIVED:
the transitive closure of those requirements, computed from the installed
distributions' own metadata for every platform the image is built on, copied block for
block -- version and hashes -- out of requirements.lock.

    python scripts/runtime_lock.py           # write requirements-gateway.lock
    python scripts/runtime_lock.py --check   # exit 1 if the committed file is stale

`make lock` runs it after compiling requirements.lock, and
tests/unit/test_toolchain_consistency.py fails when the committed file is stale (ADR-0045).
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from importlib import metadata
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parent.parent
LOCK = ROOT / "requirements.lock"
RUNTIME_LOCK = ROOT / "requirements-gateway.lock"
RUNTIME_EXTRAS = ("db", "api", "obs")

PLATFORMS: dict[str, dict[str, str]] = {
    "linux-x86_64 (GitHub Actions)": {
        "sys_platform": "linux",
        "platform_system": "Linux",
        "platform_machine": "x86_64",
        "os_name": "posix",
    },
    "linux-aarch64 (Docker on Apple Silicon)": {
        "sys_platform": "linux",
        "platform_system": "Linux",
        "platform_machine": "aarch64",
        "os_name": "posix",
    },
    "macos-arm64 (developer machine)": {
        "sys_platform": "darwin",
        "platform_system": "Darwin",
        "platform_machine": "arm64",
        "os_name": "posix",
    },
}
"""Every platform a hashed lock is installed on. pip-compile resolves only for the machine
it runs on, so each closure here is evaluated for all of them."""

HEADER = """\
# ============================================================================
# requirements-gateway.lock -- GENERATED by scripts/runtime_lock.py. Do not edit.
#
# The trace-gateway image's runtime dependencies: the project's core
# dependencies plus its db, api and obs extras, closed transitively for every
# platform the image is built on, with the SAME versions and hashes as
# requirements.lock. Regenerate with `make lock` (ADR-0045).
# ============================================================================
"""


def environments() -> list[dict[str, str]]:
    base = {key: str(value) for key, value in default_environment().items()}
    return [base | overrides for overrides in PLATFORMS.values()]


def applies(req: Requirement, envs: list[dict[str, str]], extras: frozenset[str]) -> bool:
    if req.marker is None:
        return True
    return any(
        req.marker.evaluate(env | {"extra": extra}) for env in envs for extra in ("", *extras)
    )


def lock_blocks(text: str) -> dict[str, str]:
    """Each pinned requirement's line and hash lines, keyed by canonical name, in file order."""
    blocks: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines():
        match = re.match(r"^([A-Za-z0-9][A-Za-z0-9_.\-]*)==", line)
        if match:
            current = canonicalize_name(match.group(1))
            blocks[current] = [line]
        elif current is not None and line.lstrip().startswith("--hash="):
            blocks[current].append(line)
    return {name: "\n".join(lines) for name, lines in blocks.items()}


def runtime_closure() -> set[str]:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]
    roots = [Requirement(raw) for raw in project["dependencies"]]
    for extra in RUNTIME_EXTRAS:
        roots.extend(Requirement(raw) for raw in project["optional-dependencies"][extra])
    envs = environments()
    pending = [
        (canonicalize_name(r.name), frozenset(r.extras))
        for r in roots
        if applies(r, envs, frozenset())
    ]
    seen: set[tuple[str, frozenset[str]]] = set()
    names: set[str] = set()
    while pending:
        name, extras = pending.pop()
        if (name, extras) in seen:
            continue
        seen.add((name, extras))
        names.add(name)
        for raw in metadata.distribution(name).requires or []:
            req = Requirement(raw)
            if applies(req, envs, extras):
                pending.append((canonicalize_name(req.name), frozenset(req.extras)))
    return names


def render() -> str:
    blocks = lock_blocks(LOCK.read_text())
    names = runtime_closure()
    if missing := sorted(names - set(blocks)):
        raise SystemExit(
            f"the runtime closure needs {missing}, which requirements.lock does not pin; "
            f"run `make lock`"
        )
    return HEADER + "\n".join(block for name, block in blocks.items() if name in names) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not RUNTIME_LOCK.is_file() or RUNTIME_LOCK.read_text() != rendered:
            print("requirements-gateway.lock is stale; run `make lock`")
            return 1
        print("requirements-gateway.lock matches requirements.lock")
        return 0
    RUNTIME_LOCK.write_text(rendered)
    count = len(runtime_closure())
    print(f"wrote requirements-gateway.lock ({count} pinned runtime distributions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
