"""Secret scan -- ONE definition, used identically by `make secrets` and CI.

Written after a CI failure that could not be reproduced locally, because the
Makefile target and the CI step implemented the same control two different ways
and CI additionally installed the tool UNPINNED (`pip install detect-secrets`)
while the lockfile pins 1.5.0. A security gate whose behaviour depends on which
machine runs it is not a gate.

This module therefore:
  * uses the INSTALLED (locked) detect-secrets, never a fresh unpinned install
  * reports the tool version and the scanned file count, so a failure explains
    itself without needing the CI log
  * prints every finding as file:line:type
  * exits non-zero if and only if a finding survives the baseline
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GIT = shutil.which("git") or "git"
BASELINE = ROOT / ".secrets.baseline"

# Paths that are never secrets but reliably trip entropy heuristics.
EXCLUDE_FILES = (
    r"\.venv/",
    r"\.git/",
    # Nested git worktrees of OTHER branches (parallel agents' isolated checkouts). Git
    # excludes them locally and cannot commit their files from this checkout; their
    # content is scanned here once it is integrated into this tree, like any other change.
    r"^\.claude/worktrees/",
    r"node_modules/",
    r"\.mypy_cache/",
    r"\.pytest_cache/",
    r"\.ruff_cache/",
    r"egg-info/",
    # 1800+ sha256 wheel hashes: high entropy by design, and public.
    r"^requirements\.lock$",
    # Evaluation run records and dataset freeze manifests: machine-assembled
    # files of sha256 digests and git SHAs, high entropy by design. Their field
    # sets are fixed (no free-form content), and their own integrity is checked
    # by scripts/check_claims.py and tests/unit/test_eval_v1_freeze.py.
    r"^eval/manifest/",
    r"^eval/track_a/.*\.manifest\.json$",
    # The Delta layout benchmark's machine-written results (committed) and its local run
    # output (gitignored): sha256 digests of result sets and git SHAs, like the run records
    # above, with fixed field sets (benchmarks/delta_layout/report.py). Added 2026-09-18, when
    # the first smoke run's results.json tripped the entropy heuristic.
    r"^benchmarks/delta_layout/results/",
    r"^data/bench/",
    # The event-contract release ledger: sha256 digests of committed schema
    # files, high entropy by design and public. It holds schema filenames,
    # partition keys and digests -- there is nowhere in its shape for a
    # credential to hide. Its own integrity is checked by
    # tests/contract/test_event_schemas.py.
    r"^docs/contracts/RELEASED\.json$",
    # A developer's local .env holds real local credentials BY DESIGN. It is
    # gitignored and must never be committed -- which is asserted separately by
    # check_env_is_not_committed(), a stronger control than scanning it.
    r"^\.env$",
    # Generated by `make codegen` from docs/contracts/events/*.json, which ARE
    # scanned. A secret cannot appear here without first appearing in a schema,
    # and the CI drift gate proves these files are never hand-edited. The only
    # finding is the enum member `PASSWORD_CHANGE`, an event name.
    r"^packages/trace_core/contracts/events/",
)


def tool_version() -> str:
    try:
        return version("detect-secrets")
    except PackageNotFoundError:  # pragma: no cover - install is a hard requirement
        print(
            "detect-secrets is not installed. It is part of the `dev` extra;\n"
            "run `make setup` rather than installing it ad hoc, so the version\n"
            "matches requirements.lock.",
            file=sys.stderr,
        )
        raise SystemExit(2) from None


def check_env_is_not_committed() -> list[str]:
    """`.env` holds real local credentials; it must be gitignored and untracked.

    This is the control that actually matters. Scanning the file's contents only
    produces a guaranteed false positive for every developer.
    """
    problems: list[str] = []
    tracked = subprocess.run(  # noqa: S603
        [GIT, "ls-files", "--error-unmatch", ".env"],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if tracked.returncode == 0:
        problems.append(".env is TRACKED by git. It holds local credentials and must never be.")
    ignored = subprocess.run(  # noqa: S603
        [GIT, "check-ignore", "-q", ".env"], capture_output=True, cwd=ROOT
    )
    if ignored.returncode != 0:
        problems.append(".env is not covered by .gitignore; add it before it gets committed.")
    return problems


def check_worktrees_are_not_tracked() -> list[str]:
    """`.claude/worktrees/` is excluded from the scan because nothing under it can be committed
    from this checkout. That holds only while git tracks nothing there: a force-added file would
    otherwise be committed without ever being scanned."""
    proc = subprocess.run(  # noqa: S603 -- git, a fixed argument list
        [GIT, "ls-files", "--", ".claude/worktrees"],
        capture_output=True,
        text=True,
        cwd=ROOT,
        timeout=60,
        check=False,
    )
    return [
        f"{path} is tracked by git inside .claude/worktrees/, which the scan excludes"
        for path in proc.stdout.splitlines()
        if path.strip()
    ]


def run_scan() -> dict:
    cmd = [sys.executable, "-m", "detect_secrets", "scan", "--all-files"]
    for pattern in EXCLUDE_FILES:
        cmd += ["--exclude-files", pattern]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT, timeout=300)  # noqa: S603
    if proc.returncode != 0:
        print(f"detect-secrets exited {proc.returncode}", file=sys.stderr)
        print(proc.stderr.strip()[:2000], file=sys.stderr)
        raise SystemExit(proc.returncode)
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        # This is the failure mode that produced an unexplained CI red.
        print(f"detect-secrets did not emit valid JSON: {exc}", file=sys.stderr)
        print(f"first 500 bytes of stdout:\n{proc.stdout[:500]!r}", file=sys.stderr)
        raise SystemExit(2) from exc


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--update-baseline",
        action="store_true",
        help="write the current findings to .secrets.baseline (review the diff!)",
    )
    args = ap.parse_args()

    print(f"secret-scan — detect-secrets {tool_version()}")

    if env_problems := check_env_is_not_committed():
        for problem in env_problems:
            print(f"  FAIL {problem}", file=sys.stderr)
        return 1

    if worktree_problems := check_worktrees_are_not_tracked():
        for problem in worktree_problems:
            print(f"  FAIL {problem}", file=sys.stderr)
        return 1

    report = run_scan()
    results: dict[str, list[dict]] = report.get("results", {})

    if args.update_baseline:
        BASELINE.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
        print(f"baseline written: {BASELINE.name} ({len(results)} file(s))")
        return 0

    if not results:
        print("PASS — no potential secrets detected.")
        return 0

    print(f"\n{len(results)} file(s) with potential secrets:\n", file=sys.stderr)
    for path, findings in sorted(results.items()):
        for f in findings:
            print(f"  {path}:{f.get('line_number')}: {f.get('type')}", file=sys.stderr)
    print(
        "\nIf a finding is a false positive, exclude the path in EXCLUDE_FILES "
        "with a comment explaining why, or use a placeholder value. "
        "Never commit a real credential (CLAUDE.md §9).",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
